"""
Hallucination Validator.

Validates generated interview questions and responses to prevent hallucinations:
- Checks against verified candidate profile
- Validates entity references
- Ensures grounding in retrieved knowledge
"""
from typing import Dict, Any, List, Optional
import logging

from app.ai.intelligence.rules.hallucination_rules import HallucinationRuleEngine
from app.ai.intelligence.rules.rule_engine import RuleSeverity

logger = logging.getLogger(__name__)


class HallucinationValidator:
    """
    Validates generated content to prevent hallucinations.
    
    Uses the HallucinationRuleEngine to check generated questions
    and responses before they're presented to candidates.
    """
    
    def __init__(self):
        self.rule_engine = HallucinationRuleEngine()
        self._validation_count = 0
        self._blocked_count = 0
    
    def validate_question(
        self,
        generated_question: str,
        verified_profile: Dict[str, Any],
        conversation_history: List[Dict[str, Any]],
        retrieved_context: Optional[List[Dict[str, Any]]] = None
    ) -> tuple[bool, str, Dict[str, Any]]:
        """
        Validate a generated question for hallucinations.
        
        Args:
            generated_question: The question generated by LLM
            verified_profile: Verified candidate profile data
            conversation_history: Previous conversation turns
            retrieved_context: Retrieved knowledge chunks (if any)
            
        Returns:
            (is_valid, reason, details)
            - is_valid: True if question passes validation
            - reason: Explanation of validation result
            - details: Additional validation details
        """
        self._validation_count += 1
        
        # Build context for rule engine
        context = {
            "generated_question": generated_question,
            "verified_profile": verified_profile,
            "conversation_history": conversation_history,
            "retrieved_context": retrieved_context or []
        }
        
        # Evaluate all hallucination rules
        violations = self.rule_engine.evaluate_all(context)
        
        # Check for blocker violations
        blockers = self.rule_engine.get_blocker_violations(violations)
        
        if blockers:
            self._blocked_count += 1
            reasons = [v.reason for v in blockers]
            
            logger.warning(
                f"Question blocked due to hallucination risk: {'; '.join(reasons)}",
                extra={
                    "question": generated_question[:100],
                    "blocker_count": len(blockers)
                }
            )
            
            return False, f"Hallucination detected: {'; '.join(reasons)}", {
                "violations": [v.reason for v in blockers],
                "blocked_rules": [v.rule.id for v in blockers]
            }
        
        # Check for warnings
        warnings = [v for v in violations if v.violated and v.rule.severity == RuleSeverity.WARNING]
        
        if warnings:
            warning_reasons = [v.reason for v in warnings]
            logger.info(
                f"Question validated with warnings: {'; '.join(warning_reasons)}",
                extra={"question": generated_question[:100]}
            )
            
            return True, f"Valid with warnings: {'; '.join(warning_reasons)}", {
                "warnings": warning_reasons,
                "warning_rules": [v.rule.id for v in warnings]
            }
        
        logger.debug(
            f"Question validated successfully",
            extra={"question": generated_question[:100]}
        )
        
        return True, "Valid question", {}
    
    def validate_followup(
        self,
        generated_followup: str,
        candidate_last_response: str,
        verified_profile: Dict[str, Any],
        conversation_history: List[Dict[str, Any]]
    ) -> tuple[bool, str, Dict[str, Any]]:
        """
        Validate a generated follow-up question.
        
        Args:
            generated_followup: The follow-up question generated by LLM
            candidate_last_response: Candidate's most recent response
            verified_profile: Verified candidate profile data
            conversation_history: Previous conversation turns
            
        Returns:
            (is_valid, reason, details)
        """
        self._validation_count += 1
        
        # Build context for rule engine
        context = {
            "generated_question": generated_followup,
            "generated_followup": generated_followup,
            "candidate_last_response": candidate_last_response,
            "verified_profile": verified_profile,
            "conversation_history": conversation_history
        }
        
        # Evaluate hallucination rules
        violations = self.rule_engine.evaluate_all(context)
        
        # Check for blockers
        blockers = self.rule_engine.get_blocker_violations(violations)
        
        if blockers:
            self._blocked_count += 1
            reasons = [v.reason for v in blockers]
            
            logger.warning(
                f"Follow-up blocked due to hallucination risk: {'; '.join(reasons)}",
                extra={"followup": generated_followup[:100]}
            )
            
            return False, f"Hallucination detected: {'; '.join(reasons)}", {
                "violations": [v.reason for v in blockers],
                "blocked_rules": [v.rule.id for v in blockers]
            }
        
        return True, "Valid follow-up", {}
    
    def extract_verified_facts(
        self,
        verified_profile: Dict[str, Any],
        conversation_history: List[Dict[str, Any]]
    ) -> Dict[str, List[str]]:
        """
        Extract verified facts from profile and conversation.
        
        Returns a dictionary of verified entities:
        - projects: list of project names
        - technologies: list of tech stack items
        - companies: list of companies worked at
        - skills: list of skills
        """
        verified = {
            "projects": [],
            "technologies": [],
            "companies": [],
            "skills": []
        }
        
        # Extract from profile
        if "projects" in verified_profile:
            for project in verified_profile["projects"]:
                if isinstance(project, dict):
                    verified["projects"].append(project.get("name", ""))
                else:
                    verified["projects"].append(str(project))
        
        if "skills" in verified_profile:
            verified["skills"].extend(verified_profile["skills"])
        
        if "technologies" in verified_profile:
            verified["technologies"].extend(verified_profile["technologies"])
        
        if "work_history" in verified_profile:
            for job in verified_profile["work_history"]:
                if isinstance(job, dict):
                    verified["companies"].append(job.get("company", ""))
        
        # Extract from conversation history
        # (Simplified - in production, use NER or structured extraction)
        for turn in conversation_history:
            if isinstance(turn, dict) and "candidate_response" in turn:
                response = turn["candidate_response"].lower()
                # This is a simplified extraction - enhance with proper NER
                # For now, just track what's been mentioned
        
        return verified
    
    def suggest_correction(
        self,
        invalid_question: str,
        verification_failure: Dict[str, Any]
    ) -> str:
        """
        Suggest a corrected version of an invalid question.
        
        Args:
            invalid_question: The question that failed validation
            verification_failure: Details of why validation failed
            
        Returns:
            Suggested correction or guidance
        """
        blocked_rules = verification_failure.get("blocked_rules", [])
        
        if "no_unverified_assumption" in blocked_rules:
            return "Rephrase without assuming unverified candidate experience. Ask open-ended questions to gather information first."
        
        if "no_invented_projects" in blocked_rules:
            return "Remove specific project references. Ask candidate to describe their experience first."
        
        if "no_assumed_tech_stack" in blocked_rules:
            return "Remove assumed technology references. Ask candidate what technologies they used."
        
        return "Rephrase question to avoid unverified assumptions about candidate background."
    
    def get_metrics(self) -> Dict[str, Any]:
        """Get validation metrics."""
        validation_rate = (
            (self._validation_count - self._blocked_count) / self._validation_count 
            if self._validation_count > 0 else 1.0
        )
        
        return {
            "validation_count": self._validation_count,
            "blocked_count": self._blocked_count,
            "validation_rate": validation_rate,
            "block_rate": 1.0 - validation_rate
        }
    
    def reset_metrics(self) -> None:
        """Reset validation metrics."""
        self._validation_count = 0
        self._blocked_count = 0
