"""
Topic Validator.

Validates that interview questions stay within configured domain boundaries:
- Frontend questions stay in frontend domain
- Backend questions don't drift to system design (unless configured)
- Behavioral questions maintain behavioral focus
"""
from typing import Dict, Any, List, Optional
import logging

from app.ai.intelligence.rules.topic_boundary_rules import TopicBoundaryRuleEngine
from app.ai.intelligence.rules.rule_engine import RuleSeverity

logger = logging.getLogger(__name__)


class TopicValidator:
    """
    Validates generated content to enforce topic boundaries.
    
    Uses the TopicBoundaryRuleEngine to prevent domain drift.
    """
    
    def __init__(self):
        self.rule_engine = TopicBoundaryRuleEngine()
        self._validation_count = 0
        self._drift_count = 0
    
    def validate_question(
        self,
        generated_question: str,
        interview_config: Dict[str, Any]
    ) -> tuple[bool, str, Dict[str, Any]]:
        """
        Validate that a question stays within topic boundaries.
        
        Args:
            generated_question: The question generated by LLM
            interview_config: Interview configuration (domain, type, focus)
            
        Returns:
            (is_valid, reason, details)
        """
        self._validation_count += 1
        
        # Build context for rule engine
        context = {
            "generated_question": generated_question,
            "interview_config": interview_config
        }
        
        # Evaluate topic boundary rules
        violations = self.rule_engine.evaluate_all(context)
        
        # Check for blocker violations
        blockers = self.rule_engine.get_blocker_violations(violations)
        
        if blockers:
            self._drift_count += 1
            reasons = [v.reason for v in blockers]
            
            logger.warning(
                f"Question blocked due to topic drift: {'; '.join(reasons)}",
                extra={
                    "question": generated_question[:100],
                    "configured_domain": interview_config.get("domain"),
                    "blocker_count": len(blockers)
                }
            )
            
            return False, f"Topic drift detected: {'; '.join(reasons)}", {
                "violations": [v.reason for v in blockers],
                "blocked_rules": [v.rule.id for v in blockers],
                "detected_domains": blockers[0].context.get("detected_domains", []) if blockers else []
            }
        
        # Check for warnings
        warnings = [v for v in violations if v.violated and v.rule.severity == RuleSeverity.WARNING]
        
        if warnings:
            warning_reasons = [v.reason for v in warnings]
            logger.info(
                f"Question validated with warnings: {'; '.join(warning_reasons)}",
                extra={"question": generated_question[:100]}
            )
            
            return True, f"Valid with warnings: {'; '.join(warning_reasons)}", {
                "warnings": warning_reasons,
                "warning_rules": [v.rule.id for v in warnings]
            }
        
        logger.debug(
            f"Question validated for topic boundaries",
            extra={
                "question": generated_question[:100],
                "domain": interview_config.get("domain")
            }
        )
        
        return True, "Valid question within topic boundaries", {}
    
    def get_domain_coverage(self, text: str) -> Dict[str, int]:
        """
        Get domain coverage analysis for text.
        
        Returns keyword counts for each domain.
        """
        return self.rule_engine.get_domain_coverage(text)
    
    def suggest_correction(
        self,
        invalid_question: str,
        interview_config: Dict[str, Any],
        validation_failure: Dict[str, Any]
    ) -> str:
        """
        Suggest a corrected version based on validation failure.
        
        Args:
            invalid_question: The question that failed validation
            interview_config: Interview configuration
            validation_failure: Details of validation failure
            
        Returns:
            Suggested correction guidance
        """
        blocked_rules = validation_failure.get("blocked_rules", [])
        detected_domains = validation_failure.get("detected_domains", [])
        configured_domain = interview_config.get("domain", "")
        
        if "frontend_scope_only" in blocked_rules:
            forbidden = [d for d in detected_domains if d in ["backend", "system_design"]]
            return f"Question drifted into {', '.join(forbidden)}. Rephrase to focus on {configured_domain} topics (UI, components, state management, etc.)."
        
        if "backend_scope_only" in blocked_rules:
            return f"Question drifted into frontend specifics. Rephrase to focus on {configured_domain} topics (APIs, databases, services, etc.)."
        
        if "behavioral_scope_only" in blocked_rules:
            return "Question became too technical. Rephrase to focus on behavioral aspects (experiences, decisions, teamwork, conflict resolution)."
        
        if "no_coding_in_behavioral" in blocked_rules:
            return "Remove code/implementation requests from behavioral interview. Focus on STAR-based experiences."
        
        return f"Rephrase to stay within {configured_domain} domain boundaries."
    
    def get_metrics(self) -> Dict[str, Any]:
        """Get validation metrics."""
        compliance_rate = (
            (self._validation_count - self._drift_count) / self._validation_count
            if self._validation_count > 0 else 1.0
        )
        
        return {
            "validation_count": self._validation_count,
            "drift_count": self._drift_count,
            "compliance_rate": compliance_rate,
            "drift_rate": 1.0 - compliance_rate
        }
    
    def reset_metrics(self) -> None:
        """Reset validation metrics."""
        self._validation_count = 0
        self._drift_count = 0
