from enum import Enum

class InterviewAction(Enum):
    ASK_QUESTION = "ASK_QUESTION"
    ASK_FOLLOWUP = "ASK_FOLLOWUP"
    ASK_CLARIFICATION = "ASK_CLARIFICATION"
    MOVE_TOPIC = "MOVE_TOPIC"
    PIVOT_TOPIC = "PIVOT_TOPIC"
    INTERRUPT = "INTERRUPT"
    WAIT = "WAIT"
    CHALLENGE = "CHALLENGE"
    ENCOURAGE = "ENCOURAGE"
    END_INTERVIEW = "END_INTERVIEW"
    WRAP_UP_INTERVIEW = "WRAP_UP_INTERVIEW"
