import enum


class JourneyStatus(str, enum.Enum):
    CREATED = "CREATED"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    ANALYZED = "ANALYZED"


class AnswerClassification(str, enum.Enum):
    GOOD = "GOOD"
    PARTIAL = "PARTIAL"
    VAGUE = "VAGUE"
    WRONG = "WRONG"
    STRONG_SIGNAL = "STRONG_SIGNAL"
    WEAK_SIGNAL = "WEAK_SIGNAL"
    BLUFFING = "BLUFFING"


class InterviewRoundType(str, enum.Enum):
    TECHNICAL = "TECHNICAL"
    BEHAVIORAL = "BEHAVIORAL"
    SYSTEM_DESIGN = "SYSTEM_DESIGN"
    CODING = "CODING"
    ARCHITECTURE = "ARCHITECTURE"
    HIRING_BAR = "HIRING_BAR"
    CULTURE_FIT = "CULTURE_FIT"
    HR = "HR"


class PersonaType(str, enum.Enum):
    FAANG_INTERVIEWER = "FAANG_INTERVIEWER"
    STARTUP_LEAD = "STARTUP_LEAD"
    HR_RECRUITER = "HR_RECRUITER"
    BEHAVIORAL_SPECIALIST = "BEHAVIORAL_SPECIALIST"
    BAR_RAISER = "BAR_RAISER"
    PRINCIPAL_ENGINEER = "PRINCIPAL_ENGINEER"
    FRIENDLY_MENTOR = "FRIENDLY_MENTOR"
    SKEPTICAL_ARCHITECT = "SKEPTICAL_ARCHITECT"
