"""add_candidate_memory

Revision ID: 917fd6544a85
Revises: 9d6f56a718e7
Create Date: 2026-05-24 10:34:45.602577+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '917fd6544a85'
down_revision: Union[str, None] = '9d6f56a718e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension (idempotent)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('source_session_id', sa.UUID(), nullable=True),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('decay_factor', sa.Float(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('behavioral_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_memories_candidate_id', 'candidate_memories', ['candidate_id'], unique=False)
    op.create_index('ix_candidate_memories_candidate_type', 'candidate_memories', ['candidate_id', 'memory_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_memories_candidate_type', table_name='candidate_memories')
    op.drop_index('ix_candidate_memories_candidate_id', table_name='candidate_memories')
    op.drop_table('candidate_memories')
    # ### end Alembic commands ###
