"""Add knowledge base tables

Revision ID: 14630db7abc7
Revises: e58f981d9639
Create Date: 2026-05-25 04:01:17.391980+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '14630db7abc7'
down_revision: Union[str, None] = 'e58f981d9639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_documents_difficulty', 'knowledge_documents', ['difficulty'], unique=False)
    op.create_index('ix_knowledge_documents_domain', 'knowledge_documents', ['domain'], unique=False)
    op.create_index('ix_knowledge_documents_domain_topic', 'knowledge_documents', ['domain', 'topic'], unique=False)
    op.create_index('ix_knowledge_documents_topic', 'knowledge_documents', ['topic'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('retrieval_count', sa.Integer(), nullable=False),
    sa.Column('usefulness_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_chunks_document_id', 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index('ix_knowledge_chunks_document_index', 'knowledge_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index('ix_knowledge_chunks_embedding_vector', 'knowledge_chunks', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('knowledge_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tag_type', sa.String(length=64), nullable=False),
    sa.Column('tag_value', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'tag_type', 'tag_value', name='uq_knowledge_tags_document_type_value')
    )
    op.create_index('ix_knowledge_tags_document_id', 'knowledge_tags', ['document_id'], unique=False)
    op.create_index('ix_knowledge_tags_type', 'knowledge_tags', ['tag_type'], unique=False)
    op.create_index('ix_knowledge_tags_type_value', 'knowledge_tags', ['tag_type', 'tag_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_tags_type_value', table_name='knowledge_tags')
    op.drop_index('ix_knowledge_tags_type', table_name='knowledge_tags')
    op.drop_index('ix_knowledge_tags_document_id', table_name='knowledge_tags')
    op.drop_table('knowledge_tags')
    op.drop_index('ix_knowledge_chunks_embedding_vector', table_name='knowledge_chunks', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_knowledge_chunks_document_index', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_document_id', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index('ix_knowledge_documents_topic', table_name='knowledge_documents')
    op.drop_index('ix_knowledge_documents_domain_topic', table_name='knowledge_documents')
    op.drop_index('ix_knowledge_documents_domain', table_name='knowledge_documents')
    op.drop_index('ix_knowledge_documents_difficulty', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
