"""add_career_profile

Revision ID: ae26382bd619
Revises: 3bf9e5ea905e
Create Date: 2026-05-31 17:06:23.066149+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae26382bd619'
down_revision: Union[str, None] = '3bf9e5ea905e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_role', sa.String(length=256), nullable=False),
    sa.Column('target_role', sa.String(length=256), nullable=False),
    sa.Column('resume_filename', sa.String(length=256), nullable=True),
    sa.Column('resume_content', sa.Text(), nullable=True),
    sa.Column('linkedin_filename', sa.String(length=256), nullable=True),
    sa.Column('linkedin_content', sa.Text(), nullable=True),
    sa.Column('naukri_filename', sa.String(length=256), nullable=True),
    sa.Column('naukri_content', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_career_profiles_user_id', 'career_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_career_profiles_user_id', table_name='career_profiles')
    op.drop_table('career_profiles')
    # ### end Alembic commands ###
