"""Add reference_facts

Revision ID: 48e6074d9a59
Revises: fbbb1ecfdaf9
Create Date: 2026-07-14 15:29:54.503873+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e6074d9a59'
down_revision: Union[str, None] = 'fbbb1ecfdaf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_bank', sa.Column('reference_facts', sa.String(), nullable=True))
    op.add_column('question_instances', sa.Column('reference_facts', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_instances', 'reference_facts')
    op.drop_column('question_bank', 'reference_facts')
    # ### end Alembic commands ###
