"""add_agent_persona

Revision ID: 3bf9e5ea905e
Revises: 14630db7abc7
Create Date: 2026-05-26 02:40:22.480917+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bf9e5ea905e'
down_revision: Union[str, None] = '14630db7abc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('archetype', sa.String(), nullable=False),
    sa.Column('pacing_speed', sa.Float(), nullable=False),
    sa.Column('interruption_frequency', sa.Float(), nullable=False),
    sa.Column('silence_tolerance', sa.Float(), nullable=False),
    sa.Column('skepticism_level', sa.Float(), nullable=False),
    sa.Column('technical_depth', sa.Float(), nullable=False),
    sa.Column('followup_aggressiveness', sa.Float(), nullable=False),
    sa.Column('verbosity_tolerance', sa.Float(), nullable=False),
    sa.Column('ambiguity_tolerance', sa.Float(), nullable=False),
    sa.Column('pressure_intensity', sa.Float(), nullable=False),
    sa.Column('conversational_warmth', sa.Float(), nullable=False),
    sa.Column('challenge_escalation', sa.String(), nullable=False),
    sa.Column('acknowledgment_patterns', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('custom_prompts', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('candidate_mind_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('stress_tolerance', sa.Float(), nullable=False),
    sa.Column('emotional_stability', sa.Float(), nullable=False),
    sa.Column('confidence_under_pressure', sa.Float(), nullable=False),
    sa.Column('recovery_speed', sa.Float(), nullable=False),
    sa.Column('freeze_response_risk', sa.Float(), nullable=False),
    sa.Column('communication_clarity', sa.Float(), nullable=False),
    sa.Column('response_structure', sa.Float(), nullable=False),
    sa.Column('filler_word_control', sa.Float(), nullable=False),
    sa.Column('speaking_consistency', sa.Float(), nullable=False),
    sa.Column('executive_presence', sa.Float(), nullable=False),
    sa.Column('memory_recall_strength', sa.Float(), nullable=False),
    sa.Column('strategic_thinking', sa.Float(), nullable=False),
    sa.Column('cognitive_load_tolerance', sa.Float(), nullable=False),
    sa.Column('hesitation_recovery', sa.Float(), nullable=False),
    sa.Column('pressure_handling', sa.Float(), nullable=False),
    sa.Column('technical_depth_confidence', sa.Float(), nullable=False),
    sa.Column('storytelling_ability', sa.Float(), nullable=False),
    sa.Column('behavioral_authenticity', sa.Float(), nullable=False),
    sa.Column('rolling_average_scores', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('improvement_velocity', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('confidence_trend', sa.String(), nullable=False),
    sa.Column('pressure_trend', sa.String(), nullable=False),
    sa.Column('communication_trend', sa.String(), nullable=False),
    sa.Column('weak_topics', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('strong_topics', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('recurring_failures', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('recurring_strengths', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('total_turns_analyzed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_table('learning_memory_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('concept_name', sa.String(length=255), nullable=False),
    sa.Column('concept_type', sa.String(length=64), nullable=False),
    sa.Column('familiarity_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('recall_latency', sa.Float(), nullable=False),
    sa.Column('retention_strength', sa.Float(), nullable=False),
    sa.Column('pressure_recall_stability', sa.Float(), nullable=False),
    sa.Column('retry_success_rate', sa.Float(), nullable=False),
    sa.Column('exposure_count', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.Float(), nullable=False),
    sa.Column('is_fragile', sa.Boolean(), nullable=False),
    sa.Column('is_weak_recall', sa.Boolean(), nullable=False),
    sa.Column('is_strong_recall', sa.Boolean(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_exposed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_memory_nodes_candidate_concept', 'learning_memory_nodes', ['candidate_id', 'concept_name'], unique=True)
    op.create_index('ix_learning_memory_nodes_candidate_id', 'learning_memory_nodes', ['candidate_id'], unique=False)
    op.create_table('training_journeys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.String(), nullable=False),
    sa.Column('journey_name', sa.String(), nullable=True),
    sa.Column('current_phase', sa.Integer(), nullable=False),
    sa.Column('total_phases', sa.Integer(), nullable=True),
    sa.Column('sessions_completed', sa.Integer(), nullable=False),
    sa.Column('sessions_in_current_phase', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('baseline_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('improvement_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phase_progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('journey_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success_criteria_met', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_memory_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['learning_memory_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['learning_memory_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_memory_edges_candidate_id', 'learning_memory_edges', ['candidate_id'], unique=False)
    op.create_index('ix_learning_memory_edges_source_target', 'learning_memory_edges', ['source_node_id', 'target_node_id'], unique=True)
    op.create_table('mind_state_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('mind_state_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False),
    sa.Column('mind_state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('interview_domain', sa.String(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('pressure_level', sa.String(), nullable=True),
    sa.Column('interviewer_persona', sa.String(), nullable=True),
    sa.Column('session_confidence_avg', sa.Float(), nullable=True),
    sa.Column('session_pressure_avg', sa.Float(), nullable=True),
    sa.Column('session_clarity_avg', sa.Float(), nullable=True),
    sa.Column('session_resilience_avg', sa.Float(), nullable=True),
    sa.Column('confidence_delta', sa.Float(), nullable=True),
    sa.Column('pressure_delta', sa.Float(), nullable=True),
    sa.Column('communication_delta', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mind_state_id'], ['candidate_mind_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('hesitation_seconds', sa.Float(), nullable=False),
    sa.Column('filler_word_count', sa.Integer(), nullable=False),
    sa.Column('response_latency_seconds', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('answer_quality', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confidence_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('turn_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('confidence_before', sa.Float(), nullable=True),
    sa.Column('confidence_after', sa.Float(), nullable=True),
    sa.Column('confidence_delta', sa.Float(), nullable=True),
    sa.Column('trigger_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contributing_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_description', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pressure_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('interviewer_persona', sa.String(), nullable=True),
    sa.Column('pressure_level', sa.String(), nullable=True),
    sa.Column('event_context', sa.Text(), nullable=True),
    sa.Column('candidate_response', sa.Text(), nullable=True),
    sa.Column('response_quality', sa.Float(), nullable=True),
    sa.Column('recovery_time_seconds', sa.Float(), nullable=True),
    sa.Column('composure_maintained', sa.Boolean(), nullable=True),
    sa.Column('performance_before', sa.Float(), nullable=True),
    sa.Column('performance_after', sa.Float(), nullable=True),
    sa.Column('performance_delta', sa.Float(), nullable=True),
    sa.Column('recovered_successfully', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('recovery_mode', sa.String(), nullable=False),
    sa.Column('trigger_reason', sa.String(), nullable=True),
    sa.Column('initial_answer', sa.Text(), nullable=True),
    sa.Column('initial_quality', sa.Float(), nullable=True),
    sa.Column('struggle_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('intervention_provided', sa.Text(), nullable=False),
    sa.Column('intervention_type', sa.String(), nullable=True),
    sa.Column('post_recovery_answer', sa.Text(), nullable=True),
    sa.Column('post_recovery_quality', sa.Float(), nullable=True),
    sa.Column('improvement_delta', sa.Float(), nullable=True),
    sa.Column('recovery_successful', sa.Boolean(), nullable=True),
    sa.Column('recovery_time_seconds', sa.Float(), nullable=True),
    sa.Column('confidence_restored', sa.Boolean(), nullable=True),
    sa.Column('structure_improved', sa.Boolean(), nullable=True),
    sa.Column('clarity_improved', sa.Boolean(), nullable=True),
    sa.Column('completeness_improved', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recovery_records')
    op.drop_table('pressure_events')
    op.drop_table('confidence_events')
    op.drop_table('turns')
    op.drop_table('mind_state_history')
    op.drop_index('ix_learning_memory_edges_source_target', table_name='learning_memory_edges')
    op.drop_index('ix_learning_memory_edges_candidate_id', table_name='learning_memory_edges')
    op.drop_table('learning_memory_edges')
    op.drop_table('training_journeys')
    op.drop_index('ix_learning_memory_nodes_candidate_id', table_name='learning_memory_nodes')
    op.drop_index('ix_learning_memory_nodes_candidate_concept', table_name='learning_memory_nodes')
    op.drop_table('learning_memory_nodes')
    op.drop_table('candidate_mind_states')
    op.drop_table('agent_personas')
    # ### end Alembic commands ###
