"""add_interview_journey_models

Revision ID: e58f981d9639
Revises: 917fd6544a85
Create Date: 2026-05-24 14:35:44.366935+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e58f981d9639'
down_revision: Union[str, None] = '917fd6544a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_journeys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.Column('extracted_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidate_level', sa.String(), nullable=True),
    sa.Column('role_category', sa.String(), nullable=True),
    sa.Column('generated_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interview_journeys_user_id', 'interview_journeys', ['user_id'], unique=False)
    op.create_index('ix_interview_journeys_user_id_status', 'interview_journeys', ['user_id', 'status'], unique=False)
    op.create_table('interview_journey_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('round_name', sa.String(), nullable=False),
    sa.Column('round_type', sa.String(), nullable=False),
    sa.Column('interviewer_persona', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('round_focus', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['interview_journeys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interview_journey_sessions_journey_id', 'interview_journey_sessions', ['journey_id'], unique=False)
    op.create_index('ix_interview_journey_sessions_journey_order', 'interview_journey_sessions', ['journey_id', 'order_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interview_journey_sessions_journey_order', table_name='interview_journey_sessions')
    op.drop_index('ix_interview_journey_sessions_journey_id', table_name='interview_journey_sessions')
    op.drop_table('interview_journey_sessions')
    op.drop_index('ix_interview_journeys_user_id_status', table_name='interview_journeys')
    op.drop_index('ix_interview_journeys_user_id', table_name='interview_journeys')
    op.drop_table('interview_journeys')
    # ### end Alembic commands ###
