"""update_otp_codes

Revision ID: 9d6f56a718e7
Revises: 0008_add_email_verification
Create Date: 2026-05-22 11:11:30.934917+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d6f56a718e7'
down_revision: Union[str, None] = '0008_add_email_verification'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coaching_sessions', 'focus_area',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('coaching_sessions', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('evaluation_jobs', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('evaluation_jobs', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('evaluation_jobs', 'last_error',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('evaluation_jobs_session_id_key'), 'evaluation_jobs', type_='unique')
    op.drop_index(op.f('ix_evaluation_jobs_status'), table_name='evaluation_jobs')
    op.create_index('ix_evaluation_jobs_status_evaluation_started_at', 'evaluation_jobs', ['status', 'evaluation_started_at'], unique=False)
    op.create_index('ix_evaluation_jobs_status_next_retry_at_created_at', 'evaluation_jobs', ['status', 'next_retry_at', 'created_at'], unique=False)
    op.create_unique_constraint('uq_evaluation_job_session_id', 'evaluation_jobs', ['session_id'])
    op.alter_column('evaluation_reports', 'clarity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('evaluation_reports', 'structure_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('evaluation_reports', 'depth_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('evaluation_reports', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('evaluation_reports', 'communication_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('evaluation_reports', 'hesitation_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('evaluation_reports', 'prompt_version',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('evaluation_reports', 'feedback_summary',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('evaluation_reports', 'improvement_suggestions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('evaluation_reports_session_id_key'), 'evaluation_reports', type_='unique')
    op.drop_index(op.f('ix_evaluation_reports_session_id'), table_name='evaluation_reports')
    op.create_unique_constraint('uq_evaluation_report_session_id', 'evaluation_reports', ['session_id'])
    op.drop_column('evaluation_reports', 'summary')
    op.drop_column('evaluation_reports', 'improvements')
    op.drop_column('evaluation_reports', 'difficulty_end')
    op.drop_column('evaluation_reports', 'difficulty_start')
    op.drop_column('evaluation_reports', 'strengths')
    op.alter_column('interview_sessions', 'is_voice',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('interview_sessions', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.add_column('otp_codes', sa.Column('identifier', sa.String(), nullable=False))
    op.add_column('otp_codes', sa.Column('is_used', sa.Boolean(), nullable=False))
    op.add_column('otp_codes', sa.Column('attempt_count', sa.Integer(), nullable=False))
    op.alter_column('otp_codes', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_otp_codes_user_id_expires_at'), table_name='otp_codes')
    op.create_index('ix_otp_codes_identifier', 'otp_codes', ['identifier'], unique=False)
    op.create_index('ix_otp_codes_identifier_is_used_expires_at', 'otp_codes', ['identifier', 'is_used', 'expires_at'], unique=False)
    op.drop_constraint(op.f('otp_codes_user_id_fkey'), 'otp_codes', type_='foreignkey')
    op.create_foreign_key(None, 'otp_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('otp_codes', 'used_at')
    op.drop_column('otp_codes', 'channel')
    op.alter_column('question_bank', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('question_bank', 'source',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('question_bank', 'is_global',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('question_bank', 'usage_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('question_instances', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('question_instances_bank_question_id_fkey'), 'question_instances', type_='foreignkey')
    op.drop_column('question_instances', 'interview_type')
    op.drop_column('question_instances', 'bank_question_id')
    op.alter_column('response_instances', 'answer_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('response_instances', 'response_time_ms',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('response_instances', 'thinking_time_ms',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('response_instances', 'answer_length',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('response_instances', 'transcribed_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('response_instances', 'audio_processing_status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('response_instances', 'evaluation_explanation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_response_instances_question_id'), table_name='response_instances')
    op.drop_index(op.f('ix_response_instances_session_id'), table_name='response_instances')
    op.add_column('skill_tags', sa.Column('is_global', sa.Boolean(), nullable=False))
    op.add_column('skill_tags', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.drop_column('skill_tags', 'category')
    op.alter_column('topics', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('topics', 'is_global',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('training_plans', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('training_plans', 'duration_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('training_tasks', 'estimated_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('training_tasks', 'is_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('user_context_inputs', sa.Column('raw_input', sa.String(), nullable=False))
    op.add_column('user_context_inputs', sa.Column('parsed_intent', sa.String(), nullable=True))
    op.add_column('user_context_inputs', sa.Column('extracted_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_context_inputs', sa.Column('extracted_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_context_inputs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_user_context_inputs_user_id_created_at', 'user_context_inputs', ['user_id', 'created_at'], unique=False)
    op.drop_column('user_context_inputs', 'content')
    op.drop_column('user_context_inputs', 'context_type')
    op.alter_column('user_skill_preferences', 'level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_skill_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_user_skill_preference', 'user_skill_preferences', ['user_id', 'skill_tag_id'])
    op.drop_constraint(op.f('user_skill_preferences_user_id_fkey'), 'user_skill_preferences', type_='foreignkey')
    op.drop_constraint(op.f('user_skill_preferences_skill_tag_id_fkey'), 'user_skill_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'user_skill_preferences', 'skill_tags', ['skill_tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_skill_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'plan_type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'monthly_session_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'monthly_evaluation_credits',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'monthly_evaluation_credits',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('users', 'monthly_session_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('users', 'plan_type',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'FREE'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'user_skill_preferences', type_='foreignkey')
    op.drop_constraint(None, 'user_skill_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('user_skill_preferences_skill_tag_id_fkey'), 'user_skill_preferences', 'skill_tags', ['skill_tag_id'], ['id'])
    op.create_foreign_key(op.f('user_skill_preferences_user_id_fkey'), 'user_skill_preferences', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_user_skill_preference', 'user_skill_preferences', type_='unique')
    op.alter_column('user_skill_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_skill_preferences', 'level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user_context_inputs', sa.Column('context_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_context_inputs', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index('ix_user_context_inputs_user_id_created_at', table_name='user_context_inputs')
    op.drop_column('user_context_inputs', 'deleted_at')
    op.drop_column('user_context_inputs', 'extracted_questions')
    op.drop_column('user_context_inputs', 'extracted_topics')
    op.drop_column('user_context_inputs', 'parsed_intent')
    op.drop_column('user_context_inputs', 'raw_input')
    op.alter_column('training_tasks', 'is_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('training_tasks', 'estimated_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('training_plans', 'duration_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('7'),
               existing_nullable=False)
    op.alter_column('training_plans', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'ACTIVE'::character varying"),
               existing_nullable=False)
    op.alter_column('topics', 'is_global',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('topics', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('skill_tags', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('skill_tags', 'created_by_user_id')
    op.drop_column('skill_tags', 'is_global')
    op.create_index(op.f('ix_response_instances_session_id'), 'response_instances', ['session_id'], unique=False)
    op.create_index(op.f('ix_response_instances_question_id'), 'response_instances', ['question_id'], unique=False)
    op.alter_column('response_instances', 'evaluation_explanation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('response_instances', 'audio_processing_status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'SKIPPED'::character varying"),
               existing_nullable=False)
    op.alter_column('response_instances', 'transcribed_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('response_instances', 'answer_length',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('response_instances', 'thinking_time_ms',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('response_instances', 'response_time_ms',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('response_instances', 'answer_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('question_instances', sa.Column('bank_question_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('question_instances', sa.Column('interview_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('question_instances_bank_question_id_fkey'), 'question_instances', 'question_bank', ['bank_question_id'], ['id'])
    op.alter_column('question_instances', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('question_bank', 'usage_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('question_bank', 'is_global',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('question_bank', 'source',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'HUMAN'::character varying"),
               existing_nullable=False)
    op.alter_column('question_bank', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('otp_codes', sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('otp_codes', sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'otp_codes', type_='foreignkey')
    op.create_foreign_key(op.f('otp_codes_user_id_fkey'), 'otp_codes', 'users', ['user_id'], ['id'])
    op.drop_index('ix_otp_codes_identifier_is_used_expires_at', table_name='otp_codes')
    op.drop_index('ix_otp_codes_identifier', table_name='otp_codes')
    op.create_index(op.f('ix_otp_codes_user_id_expires_at'), 'otp_codes', ['user_id', 'expires_at'], unique=False)
    op.alter_column('otp_codes', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('otp_codes', 'attempt_count')
    op.drop_column('otp_codes', 'is_used')
    op.drop_column('otp_codes', 'identifier')
    op.alter_column('interview_sessions', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'CREATED'::character varying"),
               existing_nullable=False)
    op.alter_column('interview_sessions', 'is_voice',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.add_column('evaluation_reports', sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('evaluation_reports', sa.Column('difficulty_start', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('evaluation_reports', sa.Column('difficulty_end', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('evaluation_reports', sa.Column('improvements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('evaluation_reports', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_evaluation_report_session_id', 'evaluation_reports', type_='unique')
    op.create_index(op.f('ix_evaluation_reports_session_id'), 'evaluation_reports', ['session_id'], unique=False)
    op.create_unique_constraint(op.f('evaluation_reports_session_id_key'), 'evaluation_reports', ['session_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('evaluation_reports', 'improvement_suggestions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('evaluation_reports', 'feedback_summary',
               existing_type=sa.String(),
               server_default=sa.text("''::text"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('evaluation_reports', 'prompt_version',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'stub'::character varying"),
               existing_nullable=True)
    op.alter_column('evaluation_reports', 'hesitation_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('evaluation_reports', 'communication_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('evaluation_reports', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('evaluation_reports', 'depth_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('evaluation_reports', 'structure_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('evaluation_reports', 'clarity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint('uq_evaluation_job_session_id', 'evaluation_jobs', type_='unique')
    op.drop_index('ix_evaluation_jobs_status_next_retry_at_created_at', table_name='evaluation_jobs')
    op.drop_index('ix_evaluation_jobs_status_evaluation_started_at', table_name='evaluation_jobs')
    op.create_index(op.f('ix_evaluation_jobs_status'), 'evaluation_jobs', ['status'], unique=False)
    op.create_unique_constraint(op.f('evaluation_jobs_session_id_key'), 'evaluation_jobs', ['session_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('evaluation_jobs', 'last_error',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('evaluation_jobs', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('evaluation_jobs', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=False)
    op.alter_column('coaching_sessions', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'ACTIVE'::character varying"),
               existing_nullable=False)
    op.alter_column('coaching_sessions', 'focus_area',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'general'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
