"""Add evidence fields to response_instance

Revision ID: fbbb1ecfdaf9
Revises: ae26382bd619
Create Date: 2026-07-14 15:23:16.755519+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbbb1ecfdaf9'
down_revision: Union[str, None] = 'ae26382bd619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_instances', sa.Column('clarity_evidence', sa.String(), nullable=True))
    op.add_column('response_instances', sa.Column('structure_evidence', sa.String(), nullable=True))
    op.add_column('response_instances', sa.Column('depth_evidence', sa.String(), nullable=True))
    op.add_column('response_instances', sa.Column('confidence_evidence', sa.String(), nullable=True))
    op.add_column('response_instances', sa.Column('communication_evidence', sa.String(), nullable=True))
    op.add_column('response_instances', sa.Column('technical_evidence', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_instances', 'technical_evidence')
    op.drop_column('response_instances', 'communication_evidence')
    op.drop_column('response_instances', 'confidence_evidence')
    op.drop_column('response_instances', 'depth_evidence')
    op.drop_column('response_instances', 'structure_evidence')
    op.drop_column('response_instances', 'clarity_evidence')
    # ### end Alembic commands ###
