"""update_otp_codes

Revision ID: 9d6f56a718e7
Revises: 0008_add_email_verification
Create Date: 2026-05-22 11:11:30.934917+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d6f56a718e7'
down_revision: Union[str, None] = '0008_add_email_verification'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ── otp_codes ─────────────────────────────────────────────────────────────
    op.add_column('otp_codes', sa.Column('identifier', sa.String(), nullable=False))
    op.add_column('otp_codes', sa.Column('is_used', sa.Boolean(), nullable=False))
    op.add_column('otp_codes', sa.Column('attempt_count', sa.Integer(), nullable=False))
    op.alter_column('otp_codes', 'user_id',
               existing_type=postgresql.UUID(as_uuid=True),
               nullable=True)
    op.drop_index('ix_otp_codes_user_id_expires_at', table_name='otp_codes')
    op.create_index('ix_otp_codes_identifier', 'otp_codes', ['identifier'], unique=False)
    op.create_index('ix_otp_codes_identifier_is_used_expires_at', 'otp_codes', ['identifier', 'is_used', 'expires_at'], unique=False)
    op.drop_constraint('otp_codes_user_id_fkey', 'otp_codes', type_='foreignkey')
    op.create_foreign_key(None, 'otp_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('otp_codes', 'used_at')
    op.drop_column('otp_codes', 'channel')

    # ── user_context_inputs ───────────────────────────────────────────────────
    op.add_column('user_context_inputs', sa.Column('raw_input', sa.String(), nullable=False))
    op.add_column('user_context_inputs', sa.Column('parsed_intent', sa.String(), nullable=True))
    op.add_column('user_context_inputs', sa.Column('extracted_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_context_inputs', sa.Column('extracted_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_context_inputs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_user_context_inputs_user_id_created_at', 'user_context_inputs', ['user_id', 'created_at'], unique=False)
    op.drop_column('user_context_inputs', 'content')
    op.drop_column('user_context_inputs', 'context_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ── user_context_inputs ───────────────────────────────────────────────────
    op.add_column('user_context_inputs', sa.Column('context_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_context_inputs', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index('ix_user_context_inputs_user_id_created_at', table_name='user_context_inputs')
    op.drop_column('user_context_inputs', 'deleted_at')
    op.drop_column('user_context_inputs', 'extracted_questions')
    op.drop_column('user_context_inputs', 'extracted_topics')
    op.drop_column('user_context_inputs', 'parsed_intent')
    op.drop_column('user_context_inputs', 'raw_input')

    # ── otp_codes ─────────────────────────────────────────────────────────────
    op.add_column('otp_codes', sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('otp_codes', sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'otp_codes', type_='foreignkey')
    op.create_foreign_key('otp_codes_user_id_fkey', 'otp_codes', 'users', ['user_id'], ['id'])
    op.drop_index('ix_otp_codes_identifier_is_used_expires_at', table_name='otp_codes')
    op.drop_index('ix_otp_codes_identifier', table_name='otp_codes')
    op.create_index('ix_otp_codes_user_id_expires_at', 'otp_codes', ['user_id', 'expires_at'], unique=False)
    op.alter_column('otp_codes', 'user_id',
               existing_type=postgresql.UUID(as_uuid=True),
               nullable=False)
    op.drop_column('otp_codes', 'attempt_count')
    op.drop_column('otp_codes', 'is_used')
    op.drop_column('otp_codes', 'identifier')
    # ### end Alembic commands ###
