"""Add is_followup to ResponseInstance

Revision ID: ce0de8b23d05
Revises: 48e6074d9a59
Create Date: 2026-07-14 15:35:53.011574+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0de8b23d05'
down_revision: Union[str, None] = '48e6074d9a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_instances', sa.Column('is_followup', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_instances', 'is_followup')
    # ### end Alembic commands ###
